apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@sts34.de
    privateKeySecretRef:
      name: letsencrypt-prod
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          webhook:
            config:
              apiUrl: 'https://dns.hetzner.com/api/v1'
              secretName: hetzner-secret
              zoneName: sts34.de
            groupName: acme.sts34.de
            solverName: hetzner