apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-secret
  namespace: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: test-vault-backend
  target:
    name: s3-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: backends/test/minio