apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: root
    repoURL: https://github.com/cgruenwald/gitops.git
    targetRevision: HEAD
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/replicas