
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-hetzner
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://vadimkim.github.io/cert-manager-webhook-hetzner
    targetRevision: 1.3.1
    chart: cert-manager-webhook-hetzner
    helm:
      releaseName: cert-manager-webhook-hetzner
      valuesObject:
        groupName: acme.raynet.de
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/replicas