apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
spec:
  destination:
    namespace: mongodb
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 0.11.0
    chart: community-operator
    helm:
      releaseName: community-operator
      valuesObject:
        mongodb: quay.io/mongodb
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
